[package]
name = "vater_bot"
version = "0.1.0"
authors = ["Robin Möller <moelrobi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.5"